version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=caluma
      - POSTGRES_PASSWORD=caluma
    volumes:
      - dbdata:/var/lib/postgresql/data

  caluma:
    image: ghcr.io/projectcaluma/caluma:7.14.0
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENV=development
      - LANGUAGE_CODE=en
      - LANGUAGES=en
      - CORS_ORIGIN_ALLOW_ALL=true
    command:
      [
        "/bin/sh",
        "-c",
        "wait-for-it.sh db:${DATABASE_PORT:-5432} -- ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000",
      ]

volumes:
  dbdata:
